<div class="page-wrapper">
    <div class="page-body">
        <!-- [ page content ] start -->
        <!--        <div class="row">-->
        <!-- site Analytics card start -->
        <!--            <div class="col-lg-12 col-md-12">-->
        <!--                <div class="card">-->
        <!--                </div>-->
        <!--            </div>-->

        <!--        </div>-->
        <div class="row">
            <div class="col-md-12">
                <div class="card ca-details">
                    <div class="card-header">
                        <h5 style="font-size: 30px;">Chi tiết giáo viên</h5>
                        <!--<span>Add class of <code>.form-control</code> with <code>&lt;input&gt;</code> tag</span>-->
                    </div>
                    <div class="card-block">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-default">
                                    <input type="text" name="footer-email" class="form-control" value="001">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Mã giáo viên</label>
                                </div>
                                <div class="form-group form-default">
                                    <input type="text" name="footer-email" class="form-control" value="gva">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Tên giáo viên</label>
                                </div>
                                <div class="form-group form-default">
                                    <input type="text" name="footer-email" class="form-control" value="0123456789">
                                    <span class="form-bar"></span>
                                    <label class="float-label">SĐT</label>
                                </div>
                                <div class="form-group form-default">
                                    <input type="email" name="footer-email" class="form-control" value="gva@hocmai.vn">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Email (exa@gmail.com)</label>
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-default">
                                    <input type="text" name="footer-email" class="form-control" value="Hà nội">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Địa chỉ</label>
                                </div>
                                <div class="form-group form-default">
                                    <input type="text" name="footer-email" class="form-control" value="facebook/gva">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Link facebook</label>
                                </div>
                                <div class="form-group form-default">
                                    <input type="text" name="footer-email" class="form-control" value="youtube.com">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Linh kênh youtube</label>
                                </div>
                                <div class="form-group form-default">
                                    <div class="row">
                                        <div class="col-md-10"><input type="text" name="footer-email" class="form-control" value="Bố già">
                                            <span class="form-bar"></span>
                                            <label class="float-label">Sách viết</label></div>
                                        <div class="col-md-2"><i class="ion-plus"></i></div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ page content ] end -->
    </div>
</div>