<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Quản lý thông tin sách</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
<div class="main-body">
<div class="page-wrapper">
    <div class="page-body">
        <!-- [ page content ] start -->
        <div class="row ">
            <div class="col-lg-7" style="margin-left: 22%">
                <div class="card">
                    <div class="card-header text-label-center font-text font-faauto">
                        <h4>Chỉnh Sửa Loại Sách</h4>
                        <p><?php $this->flashSession->output(); ?></p>
                    </div>
                        <div class="card-block" style="padding: 2rem">
                            <?php echo $this->tag->form(["groupbook/update/".$groups->id,"autocomplete" => "off",
                                "class" => "form-horizontal",
                                "id"    => "editgroupbook",
                                "enctype" => "multipart/form-data"]); ?>

                                <div class="form-group row">
                                    <!-- <div class="col-sm-5"> -->
                                        <!-- <div class="row"> -->
                                            <label class="col-sm-4 col-form-label  font-text text-label-center">Mã loại sách:<b style="color: red">(*)</b></label>
                                            <div class="col-sm-8">
                                                <input type="text" maxlength="2" readonly="" class="form-control" name="code"  value="<?php echo $groups->code ?>" >
                                                <span class="messages"></span>
                                            </div>
                                        <!-- </div> -->
                                    <!-- </div> -->
                                </div>
                                <div class="form-group row">
                                    <!-- <div class="col-sm-7"> -->
                                        <!-- <div class="row"> -->
                                            <label class="col-sm-4 col-form-label font-text text-label-center">Tên  loại sách:<b style="color: red">(*)</b></label>
                                            <div class="col-sm-8">
                                                <input type="text" class="form-control" name="name" value="<?php echo $groups->name ?>">
                                                <span class="messages"></span>
                                            </div>
                                        <!-- </div> -->
                                    <!-- </div> -->
                                </div>
                                <div class="pt10">
                                    <a  style="float: right; width: 100px" href="<?php echo $this->url->get('groupbook')?>" class ="btn btn-primary m-b-0 ">Đóng</a>
                                    <input style="float: right; margin-right: 20px; width: 100px" type="submit" class="btn btn-danger" value="Thêm">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>  
                <!-- site Analytics card end -->
            </div>
            <!-- [ page content ] end -->
        </div>
    </div>
</div>
</div>