<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Công Ty Đặt Hàng</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <div class="row">
                    <div class="col-md-9 text-label-center " style="margin-left: 13%;">
                        <div class="card">
                         <div class="card-header text-createcommand font-faauto font-text">
                          <h4>Chỉnh Sửa Thông Tin Công Ty</h4>
                          <p><?php $this->flashSession->output(); ?></p>
                      </div>
                      <div class="card-block">
                          <?php echo $this->tag->form(["companyorders/update/" . $companyorders->id,"autocomplete" => "off",
                           "class" => "form-horizontal",
                           "id"=>"edit_book",
                           "enctype" => "multipart/form-data"]); ?>
                           <div class="form-group row">
                            <label class="col-sm-2 col-form-label text-label-right font-text"> Tên công ty:<b style="color: red">(*)</b></label>
                            <div class="col-sm-10">
                             <input type="text" class="form-control" name="company_name" readonly=""  value="<?= $companyorders->company_name?>" >
                             <span class="messages"></span>
                         </div>
                     </div>
                     <div class="form-group row">
                        <label class="col-sm-2 col-form-label text-label-right font-text">Địa chỉ:<b style="color: red">(*)</b></label>
                        <div class="col-sm-10">
                              <input type="text" class="form-control" name="address"  value="<?= $companyorders->address?>" >
                        <span class="messages"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label text-label-right font-text">Link web:<b style="color: red">(*)</b></label>
                        <div class="col-sm-10">
                              <input type="text" class="form-control" name="linkweb"  value="<?= $companyorders->linkweb?>" >
                              <span class="messages"></span>
                        </div>
                    </div>

                <div class="mt40">  
                    <input style="float: left; width: 100px" type="reset" class="btn btn-secondary" value="Reset">
                    <a  style="float: right" href="<?php echo $this->url->get('companyorders')?>" class ="text-label-right  btn btn-primary m-b-0 ">Đóng</a>
                    <input style="float: right; margin-right: 20px; width: 100px" type="submit" class="btn btn-danger" value="Sửa">
                  
                </div>
            </div>
            </div>
            </form>
<!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>