<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Công Ty Đặt Hàng</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Công Ty Đặt Hàng</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">

		<div class="page-wrapper">
		<div class="page-body">
			<!-- [ page content ] start -->
			<div class="row">

				<!-- site Analytics card start -->

				<div class="col-lg-12 col-md-12">
					<div class="card">
						<div class="card-header font-faauto font-text">
							<h2>Công Ty Đặt Hàng</h2>
							<p><?php $this->flashSession->output(); ?></p>
						</div>
						<div class="card-block">

							<?php echo $this->tag->form(["companyorders/index","autocomplete" => "off",
								"class" => "form-horizontal",
								"id"=>"create-command",
								"method"=>"get",
								"enctype" => "multipart/form-data"]); ?>
							
								<div class="form-group row">
								
									<div class="col-sm-6">
										<div class="row">
											<label class="col-sm-3 col-form-label text-label-center">Tên công ty:</label>
											<div class="col-sm-9">
												<input type="text" placeholder="Nhập vào đây để tìm kiếm..." class="form-control border-radius" name="company_name" >
												<span class="messages"></span>
											</div>
										</div>
									</div>
									
								</div>
								<div class="form-group row">
										<div class="col-sm-12">
										<div class="pull-right">
											<input type="submit" class="btn btn-primary form-control" value="Tìm Kiếm">
										</div>
									</div>
								</div>
							</form>
				<div class="card-header pt0	">
				<a href="<?php echo $this->url->get('companyorders/create')?>" class ="btn btn-warning m-b-0 ">Thêm công ty</a>
					<span class="font-we6 font-da-cursive"  style="float: right; padding-top: 15px;">Tổng số công ty: <?= $count?></span>
				</div>
				<div class="card-block">
					<?php if(count($company) <= '0') {?>
						<label class="col-sm-12" style="text-align: center;color: red;font-size: 19px;
					    font-weight: 600;" for="">Không có kết quả tìm kiếm !</label>
					<?php } else{?>
						<div class="table-responsive dt-responsive">
							<div id="simpletable_wrapper" class="dataTables_wrapper dt-bootstrap4">
								<div class="row">
									<div class="col-xs-12 col-md-7 col-lg-12">

										<table id="dom-table" class="table table-striped table-bordered nowrap dataTable" role="grid" aria-describedby="simpletable_info">
											<thead>
												<tr role="row">

													<th class="sorting_disabled" rowspan="1" colspan="1">STT</th>
													<th class="sorting_disabled" rowspan="1" colspan="1">Tên công ty</th>
													<th class="sorting_disabled" rowspan="1" colspan="1">Địa chỉ</th>
													<th class="sorting_disabled" rowspan="1" colspan="1">Link web</th>
													<th class="sorting_disabled" rowspan="1" colspan="3">Tùy Chọn</th>
												</tr>
											</thead>
											<tbody>
												<?php foreach($company as $key=>$companys) {?>
													<tr>
														<td><?php echo ($off) + ($key + 1) ?></td>
														<td><?php echo $companys->company_name ?></td>
														<td><?php echo $companys->address ?></td>
														<td><?php echo $companys->linkweb; ?></td>	
														<td>
															<a class="btn btn-primary icon-table" href="<?php echo $this->url->get('companyorders/edit/'.$companys->id)?>" title="">
																<span class='icofont icofont-ui-edit'></span>
															</a>
															<a class="btn btn-danger icon-table" href ="<?php echo $this->url->get('companyorders/delete/'.$companys->id)?>" onclick="return confirm(' Bạn có muốn xóa mục này?');"  title="">
																<span class='icofont icofont-ui-delete'></span>
															</a>
														</td>
													</tr>
												<?php }?>

												</tbody>
											</table>
										<?php }?>
									</div>
								</div>
							</div>
							
						</div>

						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-5">
								<div class="dataTables_info" id="footer-search_info" role="status" aria-live="polite">
									
								</div>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-7">
								<div class="dataTables_paginate paging_simple_numbers" id="footer-search_paginate">
									<?php if ($paginator->getNumPages() > 1): ?>
										<ul class="pagination">
											<?php if ($paginator->getPrevUrl()): ?>
												<li class="paginate_button page-item previous" id="footer-search_previous"><a aria-controls="footer-search" data-dt-idx="0" tabindex="0" class="page-link" href="<?php echo $paginator->getPrevUrl(); ?>">&laquo; Previous</a></li>
											<?php endif; ?>

											<?php foreach ($paginator->getPages() as $page): ?>
												<?php if ($page['url']): ?>
													<li class="paginate_button page-item <?php echo $page['isCurrent'] ? 'active' : ''; ?>">
														<a aria-controls="footer-search" data-dt-idx="<?= $key + 1?>" tabindex="0" class="page-link" href="<?php echo $page['url']; ?>"><?php echo $page['num']; ?></a>
													</li>
													<?php else: ?>
														<a aria-controls="footer-search" data-dt-idx="<?= $key +1?>" tabindex="0" class="page-link" href="<?php echo $page['url']; ?>"><?php echo $page['num']; ?></a>
													<?php endif; ?>
												<?php endforeach; ?>

												<?php if ($paginator->getNextUrl()): ?>
													<li class="paginate_button page-item next" id="footer-search_next"><a aria-controls="footer-search" data-dt-idx="7" tabindex="0" class="page-link" href="<?php echo $paginator->getNextUrl(); ?>">Next &raquo;</a></li>
												<?php endif; ?>
											</ul>
										<?php endif; ?>

									</div>
								</div>
							</div>
						</div>
					</div>  
				</div>
			</div>
		</div>
	</div>
				
	</div>
</div>