<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Dashboard</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Dashboard</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="row">

                    <!-- customar project  start -->
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-book f-30 text-c-purple"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">Tickets Answered</h6>
                                        <h2 class="m-b-0">379</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-navigation-2 f-30 text-c-green"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">Projects Launched</h6>
                                        <h2 class="m-b-0">205</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-users f-30 text-c-red"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">Happy Customers</h6>
                                        <h2 class="m-b-0">5984</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-award f-30 text-c-blue"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">Unique Innovation</h6>
                                        <h2 class="m-b-0">325</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- customar project  end -->

                    <div class="col-xl-5 col-md-12">
                        <div class="card latest-update-card">
                            <div class="card-header">
                                <h5>Latest Updates</h5>
                                <div class="card-header-right">
                                    <ul class="list-unstyled card-option">
                                        <li class="first-opt"><i class="feather icon-chevron-left open-card-option"></i></li>
                                        <li><i class="feather icon-maximize full-card"></i></li>
                                        <li><i class="feather icon-minus minimize-card"></i></li>
                                        <li><i class="feather icon-refresh-cw reload-card"></i></li>
                                        <li><i class="feather icon-trash close-card"></i></li>
                                        <li><i class="feather icon-chevron-left open-card-option"></i></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-block">
                                <div class="latest-update-box">
                                    <div class="row p-t-20 p-b-30">
                                        <div class="col-auto text-right update-meta">
                                            <p class="text-muted m-b-0 d-inline">4 hrs ago</p>
                                            <i class="feather icon-briefcase bg-c-red update-icon"></i>
                                        </div>
                                        <div class="col">
                                            <h6>+ 5 New Products were added!</h6>
                                            <p class="text-muted m-b-0">Congratulations!</p>
                                        </div>
                                    </div>
                                    <div class="row p-b-30">
                                        <div class="col-auto text-right update-meta">
                                            <p class="text-muted m-b-0 d-inline">1 day ago</p>
                                            <i class="feather icon-check f-w-600 bg-c-green update-icon"></i>
                                        </div>
                                        <div class="col">
                                            <h6>Database backup completed!</h6>
                                            <p class="text-muted m-b-0">Download the <span class="text-c-blue"> <a href="#!" class="text-c-blue">latest backup</a> </span>.</p>
                                        </div>
                                    </div>
                                    <div class="row p-b-0">
                                        <div class="col-auto text-right update-meta">
                                            <p class="text-muted m-b-0 d-inline">2 day ago</p>
                                            <i class="feather icon-facebook bg-facebook update-icon"></i>
                                        </div>
                                        <div class="col">
                                            <h6>+2 Friend Requests</h6>
                                            <p class="text-muted m-b-10">This is great, keep it up!</p>
                                            <div class="table-responsive">
                                                <table class="table table-hover">
                                                    <tbody>
                                                        <tr>
                                                            <td class="b-none">
                                                                <a href="#!" class="align-middle">
                                                                    <img src="../files/assets/images/avatar-2.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                                    <div class="d-inline-block">
                                                                        <h6>Jeny William</h6>
                                                                        <p class="text-muted m-b-0">Graphic Designer</p>
                                                                    </div>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-12">
                        <div class="card task-card">
                            <div class="card-header">
                                <h5>Tasks</h5>
                                <div class="card-header-right">
                                    <ul class="list-unstyled card-option">
                                        <li class="first-opt"><i class="feather icon-chevron-left open-card-option"></i></li>
                                        <li><i class="feather icon-maximize full-card"></i></li>
                                        <li><i class="feather icon-minus minimize-card"></i></li>
                                        <li><i class="feather icon-refresh-cw reload-card"></i></li>
                                        <li><i class="feather icon-trash close-card"></i></li>
                                        <li><i class="feather icon-chevron-left open-card-option"></i></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-block">
                                <ul class="list-unstyled task-list">
                                    <li>
                                        <i class="feather icon-check f-w-600 task-icon bg-c-green"></i>
                                        <p class="m-b-5">8:50</p>
                                        <h6 class="text-muted">Call to customer <span class="text-c-blue"> <a href="#!" class="text-c-blue">Jacob</a> </span> and discuss the</h6>
                                    </li>
                                    <li>
                                        <i class="task-icon bg-c-blue"></i>
                                        <p class="m-b-5">Sat, 5 Mar</p>
                                        <h6 class="text-muted">Design mobile Application</h6>
                                    </li>
                                    <li>
                                        <i class="task-icon bg-c-red"></i>
                                        <p class="m-b-5">Sun, 17 Feb</p>
                                        <h6 class="text-muted"><span class="text-c-blue"><a href="#!" class="text-c-blue">Jeny</a></span> assign you a task <span class="text-c-blue"><a href="#!" class="text-c-blue">Mockup Design.</a></span></h6>
                                    </li>
                                    <li class="p-b-10">
                                        <i class="task-icon bg-c-yellow"></i>
                                        <p class="m-b-5">Sat, 18 Mar</p>
                                        <h6 class="text-muted">Design logo</h6>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- prject ,team member start -->
                    <div class="col-xl-6 col-md-12">
                        <div class="card table-card">
                            <div class="card-header">
                                <h5>Projects</h5>
                                <div class="card-header-right">
                                    <ul class="list-unstyled card-option">
                                        <li class="first-opt"><i class="feather icon-chevron-left open-card-option"></i></li>
                                        <li><i class="feather icon-maximize full-card"></i></li>
                                        <li><i class="feather icon-minus minimize-card"></i></li>
                                        <li><i class="feather icon-refresh-cw reload-card"></i></li>
                                        <li><i class="feather icon-trash close-card"></i></li>
                                        <li><i class="feather icon-chevron-left open-card-option"></i></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-block">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                <input type="checkbox" id="selectall"/>
                                                                <span class="cr">
                                                                    <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                </span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    Assigned</th>
                                                <th>Name</th>
                                                <th>Due Date</th>
                                                <th class="text-right">Priority</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="1"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-4.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>John Deo</h6>
                                                            <p class="text-muted m-b-0">Graphics Designer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Able Pro</td>
                                                <td>Jun, 26</td>
                                                <td class="text-right"><label class="label label-danger">Low</label></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="2"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-2.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>Jenifer Vintage</h6>
                                                            <p class="text-muted m-b-0">Web Designer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Mashable</td>
                                                <td>March, 31</td>
                                                <td class="text-right"><label class="label label-primary">high</label></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="3"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-3.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>William Jem</h6>
                                                            <p class="text-muted m-b-0">Developer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Flatable</td>
                                                <td>Aug, 02</td>
                                                <td class="text-right"><label class="label label-success">medium</label></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="4"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-2.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>David Jones</h6>
                                                            <p class="text-muted m-b-0">Developer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Guruable</td>
                                                <td>Sep, 22</td>
                                                <td class="text-right"><label class="label label-primary">high</label></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="text-right m-r-20">
                                        <a href="#!" class=" b-b-primary text-primary">View all Projects</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Active Tickets, Latest Posts end -->

                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>