<div class="page-wrapper">
	<div class="page-body">
		<!-- [ page content ] start -->
		<div class="row">
			<!-- site Analytics card start -->
			<div class="col-lg-12 col-md-12">
				<div class="card ca-details">
					<div class="card-header  font-text text-label-center  font-faauto">
						<h4>Chi Tiết Sách <u style="color: chocolate"><i> <?= $book->name?> </i></u></h4>
						<p>
							<?php $this->flashSession->output(); ?></p>
						</div>
						<div class="card-block ">
							<div class="form-group row">
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">Mã sách:</label>
										<div class="col-sm-7">
											<label class="col-form-label"><?= $book->code?></label>
										</div>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">Loại sách:</label>
										<div class="col-sm-7">
											<label class="col-form-label "><?=$book->BookGroup->name?></label>
										</div>
									</div>
								</div>
							</div>
							<div class="form-group row">
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">Tên sách:</label>
										<div class="col-sm-7">
											<label class="col-form-label"><?= $book->name?></label>
										</div>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">Giá:</label>
										<div class="col-sm-7">
											<label class="col-form-label">
												<?php if($book->price){ ?>
													<?= $book->price?><strong>đ</strong>
												<?php } ?>
											</label>
										</div>
									</div>
								</div>
							</div>
							<div class="form-group row">
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">Phụ trách:</label>
										<div class="col-sm-7">

											<select  disabled="" multiple="multiple" class="js-example-tokenizer col-sm-12">
												<?php foreach ($teachers as $key => $val){ ?>
													<option value="<?php echo $val->code ?>"
														<?php foreach($book->BookTeacher as $value){ ?>
															<?php echo $value->teacher_code == $val->code ? 'selected' : '' ?>
														<?php } ?>
														>
														<?php echo $val->fullname?>
													</option>
												<?php }?>
											</select>
										</div>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">HDSD:</label>
										<div class="col-sm-7">
											<label class="col-form-label"><?= $book->attachs?></label>
										</div>
									</div>
								</div>
							</div>
							<div class="form-group row">
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">Thời gian tạo:</label>
										<div class="col-sm-7">
											<label class="col-form-label"><?= $book->created_at?></label>
										</div>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="row">
										<label class="col-sm-5 col-form-label font-text text-label-right">Thời gian cập nhật:</label>
										<div class="col-sm-7">
											<label class="col-form-label"><?= $book->updated_at?></label>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="card ca2-details">
						<div class="card-header">
							<button data-toggle="modal" data-target="#addtaiban" class ="btn btn-warning ">Tạo mã in</button>
							<!-- <div> -->
								<label class="font-we6 font-da-cursive"  style="float: right;">Tổng số lượt tái bản: <?php echo $countrepub?></label>
								<!-- </div> -->
							</div>
							<div class="card-block" style="text-align: center;">
								<div class="dt-responsive">
									<div id="simpletable_wrapper" class="dataTables_wrapper dt-bootstrap4">
										<div class="row">
											<div class="col-xs-12 col-md-7 col-lg-12">
												<table id="dom-table" class="table table-striped table-bordered nowrap dataTable icon-list-demo" role="grid" aria-describedby="simpletable_info">
													<thead>
														<tr role="row">
															<th class="sorting_disabled" rowspan="1" colspan="1"> Đợt tái bản
															</th>
															<th class="sorting_disabled" rowspan="1" colspan="1">Số lượng</th>
															<th class="sorting_disabled" rowspan="1" colspan="3">Tùy Chọn</th>

														</tr>
													</thead>
													<tbody>
														<?php foreach($arr as $val) { 

															?>

															<tr>
																<td  class="attr-id" data-code ="<?php echo $book->code ?>" data-attr = "<?php echo $val['republish']?>">
																	<?= $val['republish'] ?></td>
																	<td class="total" data-total ="<?= $val['total']?>"><?= $val['total']?>
																	<input type="text" name="getdata" hidden="" value="<?php echo $book->code ?>">
																</td>
																<td>
																	<a class="btn btn-info icon-table" id="detais" title="" geturl="<?php echo $this->url->get('book/detailscode/')?>">
																		<span class="zmdi zmdi-menu"></span>
																	</a>

																	<a get-code="<?php echo $this->url->get('book/download/')?>"  class="btn btn-primary icon-table" id="downloadcode"   title="">
																		<!-- data-toggle="modal" data-target="#download" -->
																		<span class='icofont icofont-download-alt'></span>
																	</a>

																</td>
															</tr>
														<?php }?>

													</tbody>
												</table>
											</div>
										</div>

									</div>
								</div>
								<div>
									<a  style="float: right" href="<?php echo $this->url->get('book')?>" class ="btn btn-primary m-b-0 ">Đóng</a>
								</div>
							</div>
						</div>
					</div>

				</div>  
			</div>

			<!-- site Analytics card end -->
		</div>

		<!-- [ page content ] end -->
	</div>
</div>
<div class="modal fade" id="addtaiban" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title font-text">Thêm Tái Bản</h4>
			</div>
			<div class="modal-body">
				<?php echo $this->tag->form(["book/republist","autocomplete" => "off",
					"class" => "form-horizontal",
					"id" => "republist",
					"enctype" => "multipart/form-data"]); ?>
					<div class="form-group row">
						<div class="col-sm-10">
							<div class="row">
								<label class="col-sm-5 col-form-label text-label-right">Mã sách:</label>
								<div class="col-sm-7">
									<label class="col-form-label"><?= $book->code?></label>
								</div>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<div class="col-sm-10">
							<div class="row">
								<label class="col-sm-5 col-form-label text-label-right">Số lượng tái bản (*)</label>
								<div class="col-sm-7">
									<input type="number" min="1" class="form-control" name="number" id="book_code" >
									<input type="text" hidden="" class="form-control" value="<?=$book->code?>" name="book_code" >
									<input type="text" name="geturl" hidden="" value="<?=$book->id?>">
									<input type="text" hidden="" class="form-control" value="<?php echo $countrepub?>" name="count" >
									<select hidden="" id="code_item" name="code_item" class="browser-default custom-select">
										<?php foreach($group_id as $key=>$val ) { ?>
											<option value="<?php echo $val->code ?>" <?php echo $book->group_id == $val->id ? 'selected' : '' ?>>
												<?php echo $val->code?></option>
											<?php } ?>
										</select>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="submit" class="btn  btn-warning">Thêm</button>
							<button type="button" class="btn btn-primary resetform" data-dismiss="modal">Đóng</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Số lượng mã in: <span class="totalbook"></span>/<span class="countrepublishs"></span> <br> Chi tiết xin vui lòng tải về  và xem dưới dạng file excel</h5>
				</div>
				<div class="modal-body">
					<div class="card-block">
						<div class="dt-responsive">
							<div id="simpletable_wrapper" class="dataTables_wrapper dt-bootstrap4">
								<div class="row">
									<div class="col-xs-12 col-md-7 col-lg-12">
										<table id="dom-table" class="table table-striped table-bordered nowrap dataTable" role="grid" aria-describedby="simpletable_info">
											<tbody id="listitem">

											</tbody>
										</table>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" id="download" role="dialog">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title title-dowload1">Bạn có muốn tải xuống mã sách in đợt tái bản này không?</h4>
					<h4 class="modal-title title-dowload2" style="display: none;">Download Thành Công</h4>
				</div>
				<div class="modal-body getdulieu">
					<div class="form-group row">
						<div class="col-sm-10">
							<div class="row">
								<label class="col-sm-5 col-form-label text-label-right">Số lượng mã in:</label>
								<div class="col-sm-7">
									<label class="col-form-label downloadcode"></label>
									<label class="col-form-label attr-code" hidden=""></label>
								</div>

							</div>
						</div>
					</div>
					<div class="col-md-12 progress-d-none">
						<div class="progress" style="display: none;">
							<div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
						
						<div style="text-align: center;">
							<label  class="linkdownload"></label>
						</div>
					</div>

				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-default closedowload" data-dismiss="modal">Không</button>
					<button type="submit" class="btn btn-primary downloadcodebook">Có</button>
					<button type="button" class="btn btn-default resetdowload" data-dismiss="modal">Đóng</button>
				</div>
			</div>

		</div>
	</div>

