<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Quản Lý Sách</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Quản Lý Sách</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">

		<div class="page-wrapper">
		<div class="page-body">
			<!-- [ page content ] start -->
			<div class="row">

				<!-- site Analytics card start -->

				<div class="col-lg-12 col-md-12">
					<div class="card">
						<div class="card-header  font-text font-faauto">
							<h2>Quản Lý Sách</h2>
							<p><?php $this->flashSession->output(); ?></p>
						</div>
						<div class="card-block">

							<?php echo $this->tag->form(["","autocomplete" => "off",
								"class" => "form-horizontal",
								"id"=>"create-command",
								"method"=>"get",
								"enctype" => "multipart/form-data"]); ?>
							
								<div class="form-group row">
									<div class="col-sm-4">
										<div class="row">
											<label class="col-sm-5 col-form-label text-label-right  font-text">Loại sách:</label>
											<div class="col-sm-7">
												<select name="group_id" class="browser-default custom-select">
													<option value="">---Chọn loại sách---</option>
													<?php foreach($group_ids as $key=>$val )
													{?>
														<option value="<?php echo $val->id ?>" <?php echo $val->id == $group_id ? 'selected' : ''?>><?php echo $val->name?></option>

													<?php } ?>
												</select>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="row">
											<label class="col-sm-5 col-form-label text-label-right  font-text">Tên sách:</label>
											<div class="col-sm-7">
												<input type="text" class="form-control border-radius"  placeholder="Nhập tên sách..." name="name" value="<?php echo  $name ? $name : ''?>" >
												<span class="messages"></span>
											</div>
										</div>
									</div>
									
									<div class="col-sm-4">
										<div class="row">
											<label class="col-sm-5 col-form-label text-label-right  font-text">Nhân viên:</label>
											<div class="col-sm-7">
												<select name="teacher" class="browser-default custom-select">
													<option value="">---Chọn nhân viên---</option>
													<?php foreach($teachers as $key => $val) {?>
														<option value="<?= $val->code ?>" <?php echo $val->code == $teacher ? 'selected' :''?>> <?= $val->fullname ?></option>
													<?php }?>
												</select>
											</div>
										</div>
									</div>
								</div>
								<div class="form-group row">
									<div class="col-sm-4">
										<div class="row">
											<label class="col-sm-5 col-form-label text-label-right  font-text">Từ ngày:</label>
											<div class="col-sm-7">
												<input name="startDate" value="<?php echo $startDate ? $startDate :'' ?>" class="form-control" type="date"/>
												<span class="messages"></span>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="row">
											<label class="col-sm-5 col-form-label text-label-right  font-text">Đến ngày:</label>
											<div class="col-sm-7">
												<input  name="endDate" value="<?php echo $endDate ? $endDate :'' ?>"  class="form-control" type="date"/>
												<span class="messages"></span>
											</div>
										</div>
									</div>
									<!-- <div class="col-sm-4">
										<div class="row">
											<label class="col-sm-5 col-form-label text-label-right  font-text" >Lớp:</label>
											<div class="col-sm-7">
												<select name="class_id" class="browser-default custom-select">
													<option></option>
													<?php $x = 1; for($x; $x<=12; $x++){?>
														<option value="<?php echo $x ?>"<?php echo $x == $class_id ? 'selected' : '' ?>><?php echo $x?></option>
													<?php } ?>
												</select>
											</div>
										</div>
									</div> -->
								</div>
								<div class="form-group row">
										<div class="col-sm-12">
										<div class="pull-right">
											<input type="submit" class="btn btn-primary form-control" value="Tìm Kiếm">
										</div>
									</div>
								</div>
							</form>
			<div class="card-header">
				<a href="<?php echo $this->url->get('book/create')?>" class ="btn btn-warning m-b-0 ">Thêm mới sách</a>
					<span   class="font-we6 font-da-cursive" style="float: right; padding-top: 15px;">Tổng số sách: <?= $count?></span>
				</div>
				<div class="card-block">
					<?php if(count($books) <= '0') {?>
						<label class="col-sm-12" style="text-align: center;color: red;font-size: 19px;
    font-weight: 600;" for="">Không có kết quả tìm kiếm !</label>
					<?php } else{?>
						<div class="table-responsive dt-responsive">
							<div id="simpletable_wrapper" class="dataTables_wrapper dt-bootstrap4">
								<div class="row">
									<div class="col-xs-12 col-md-7 col-lg-12">

										<table id="dom-table" class="table table-striped table-bordered nowrap dataTable" role="grid" aria-describedby="simpletable_info">
											<thead>
												<tr role="row">

													<th class="sorting_disabled" rowspan="1" colspan="1">STT</th>
													<th class="sorting_disabled" rowspan="1" colspan="1">Mã sách</th>
													<th class="sorting_disabled" rowspan="1" colspan="1">Loại sách</th>
													<th class="sorting_disabled" rowspan="1" colspan="1">Tên sách</th>
													<!-- <th class="sorting_disabled" rowspan="1" colspan="1">Lớp</th> -->
												<!-- 	<th class="sorting_disabled" rowspan="1" colspan="1">
													Hdsd</th> -->
													<th class="sorting_disabled" rowspan="1" colspan="1"> Ngày tạo</th>
													<th class="sorting_disabled" rowspan="1" colspan="3">Tùy Chọn</th>
												</tr>
											</thead>
											<tbody>
												<?php foreach($books as $key=>$book) {?>
													<tr>
														<td><?php echo ($off) + ($key + 1) ?></td>
														<td><?php echo $book->code ?></td>
														<td><?php echo $book->BookGroup->name ?></td>
														<td><?php echo $book->name ?></td>
														<!-- <td><?php echo $book->class_id ?></td> -->
														<!-- <td><?php echo $book->attachs ?></td> -->
														<td><?php echo date("d-m-Y H:m:i", strtotime($book->created_at)); ?></td>


														<td>
															<a class="btn btn-info icon-table" href="<?php echo $this->url->get('book/detail/'.$book->id)?>" title="">
																<span class="zmdi zmdi-menu"></span>
															</a>

															<a class="btn btn-primary icon-table" href="<?php echo $this->url->get('book/edit/'.$book->id)?>" title="">
																<span class='icofont icofont-ui-edit'></span>
															</a>
															<a class="btn btn-danger icon-table" href ="<?php echo $this->url->get('book/delete/'.$book->id)?>" onclick="return confirm(' Bạn có muốn xóa mục này?');"  title="">
																<span class='icofont icofont-ui-delete'></span>
															</a>
														</td>
													</tr>
												<?php }?>

												</tbody>
											</table>
										<?php }?>
									</div>
								</div>
							</div>
							
						</div>

						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-5">
								<div class="dataTables_info" id="footer-search_info" role="status" aria-live="polite">
									
								</div>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-7">
								<div class="dataTables_paginate paging_simple_numbers" id="footer-search_paginate">
									<?php if ($paginator->getNumPages() > 1): ?>
										<ul class="pagination">
											<?php if ($paginator->getPrevUrl()): ?>
												<li class="paginate_button page-item previous" id="footer-search_previous"><a aria-controls="footer-search" data-dt-idx="0" tabindex="0" class="page-link" href="<?php echo $paginator->getPrevUrl(); ?>">&laquo; Previous</a></li>
											<?php endif; ?>

											<?php foreach ($paginator->getPages() as $page): ?>
												<?php if ($page['url']): ?>
													<li class="paginate_button page-item <?php echo $page['isCurrent'] ? 'active' : ''; ?>">
														<a aria-controls="footer-search" data-dt-idx="<?= $key + 1?>" tabindex="0" class="page-link" href="<?php echo $page['url']; ?>"><?php echo $page['num']; ?></a>
													</li>
													<?php else: ?>
														<a aria-controls="footer-search" data-dt-idx="<?= $key +1?>" tabindex="0" class="page-link" href="<?php echo $page['url']; ?>"><?php echo $page['num']; ?></a>
													<?php endif; ?>
												<?php endforeach; ?>

												<?php if ($paginator->getNextUrl()): ?>
													<li class="paginate_button page-item next" id="footer-search_next"><a aria-controls="footer-search" data-dt-idx="7" tabindex="0" class="page-link" href="<?php echo $paginator->getNextUrl(); ?>">Next &raquo;</a></li>
												<?php endif; ?>
											</ul>
										<?php endif; ?>

									</div>
								</div>
							</div>
						</div>
					</div>  
				</div>
			</div>
		</div>
	</div>
				
	</div>
</div>