<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Quản lý tin nhắn hợp lệ</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Quản lý tin nhắn hợp lệ</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">


        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="row"  style="font-size: 14px;">
                    <!-- site Analytics card start -->
                    <div class="col-lg-12 col-md-12">

                        <!-- Basic Form Inputs card end -->
                        <!-- Input Grid card start -->
                        <div class="card">
                            <div class="card-block">
                                <h5 class="sub-title" style="font-size: 32px; font-family: 'Open Sans',sans-serif; font-weight: 600;">Quản lý tin nhắn hợp lệ</h5>
                                <form action="" method="get">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <div class="row">
                                                <div class="col-md-4"><label style="margin-top: 10px">SĐT</label></div>
                                                <div class="col-md-8"><input type="text" class="form-control" placeholder="0123456789" name="phone" value="<?php echo $phone ? $phone : "" ?>"></div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="row">
                                                <div class="col-md-4"><label style="margin-top: 10px">Email</label></div>
                                                <div class="col-md-8"><input type="text" class="form-control" placeholder="a@hocmai.vn" name="email" value="<?php echo $email ? $email : "" ?>" ></div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="row">
                                                <div class="col-md-4"><label style="margin-top: 10px">Mã in</label></div>
                                                <div class="col-md-8"><input type="text" class="form-control" placeholder="T01" name="code" value="<?php echo $code ? $code : "" ?>" style="margin-left: -10px;"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">

                                        <div class="col-md-4">
                                            <div class="row">
                                                <div class="col-md-4"><label style="margin-top: 10px">Từ ngày</label></div>
                                                <div class="col-md-8">
                                                    <input class="form-control" style="width: 100%; height: 36px" type="date" name="startDate" value="<?php echo $startDate ? $startDate : "" ?>">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="row">
                                                <div class="col-md-4"><label style="margin-top: 10px">Đến ngày</label></div>
                                                <div class="col-md-8">
                                                    <input class="form-control" style="width: 100%; height: 36px" type="date" name="endDate" value="<?php echo $endDate ? $endDate : "" ?>">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="row">
                                                <div class="col-md-4"><label style="margin-top: 10px">Trạng thái</label></div>
                                                <div class="col-md-8" style="margin-left: -10px;">
                                                    <select name="status" style="width: 100%; height: 36px" >
                                                        <option value="">Chọn trạng thái</option>
                                                        <option value="1" <?php if ($status == '1') echo 'selected'?>>Đã gửi</option>
                                                        <option value="0" <?php if ($status == '0') echo 'selected'?>>Chưa gửi</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="form-group row">
                                        <div class="col-lg-8"></div>
                                        <div class="col-md-4">
                                            <div class="row">
                                                <div class="col-md-8"></div>
                                                <div class="col-md-4"><button type="submit" class="btn btn-primary btn-sm">Tìm kiếm</button></div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>
                        <!-- Input Grid card end -->
                        <div class="card">
                            <div class="card-header">
                                <span>Tổng số tin nhắn hợp lệ: <?php echo count($paginate) ?></span>
                            </div>
                            <div class="card-block">
                                <div class="dt-responsive table-responsive">
        <!--                            --><?php //var_dump($a);?>
                                    <?php if (count($validmessage) > '0') { ?>
                                    <table id="simpletable" class="table table-striped table-bordered nowrap">
                                        <thead>
                                        <tr>
                                            <th style="text-align: center;">STT</th>
                                            <th style="text-align: center;">SĐT</th>
                                            <th style="text-align: center;">Mã in</th>
                                            <th style="text-align: center;">Môn</th>
                                            <th style="text-align: center;">Email</th>
                                            <th style="text-align: center;">Trạng thái</th>
                                            <th style="text-align: center;">Ngày nhận tin</th>
<!--                                            <th>Tùy chọn</th>-->
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($validmessage as $key=>$value) { ?>
                                            <tr>
                                                <td style="text-align: center;"><?php echo ($off)+($key+1) ?></td>
                                                <td><?php echo $value->phone ?></td>
                                                <td style="text-align: center;"><?php echo $value->Republish ? $value->Republish->code_item : NULL ?></td>
                                                <td><?php $ab = $value->Republish ? $value->Republish : NULL;
                                                    if ($ab) echo $ab->Book ? $value->Republish->Book->name : NULL ?></td>
                                                <td><?php echo $value->email ?></td>
                                                <td style="text-align: center;"><?php echo $value->send_mail == 0 ? "Chưa gửi" : "Đã gửi" ?></td>
                                                <td style="text-align: center;"><?php echo date_format( new DateTime($value->created_at), 'd/m/Y' ) ?></td>
<!--                                                <td>-->
<!--                                                    <a class="btn btn-primary btn-sm icon-table"data-toggle="modal" data-target="#download" title="">-->
<!--                                                        <i class="ion-ios-email" style="font-size: 19px;"></i>-->
<!--                                                    </a>-->
<!--                                                </td>-->
                                            </tr>
                                        <?php } ?>
        <!--                                    <tr>-->
        <!--                                        <td>1</td>-->
        <!--                                        <td>10329424032</td>-->
        <!--                                        <td>1V020001</td>-->
        <!--                                        <td>Tiếng việt 2</td>-->
        <!--                                        <td>tiennq@hocmai.vn</td>-->
        <!--                                        <td>Đã duyệt</td>-->
        <!--                                        <td>24/09/2019</td>-->
        <!--                                        <td>-->
        <!--                                            <a class="btn btn-primary btn-sm icon-table"data-toggle="modal" data-target="#download" title="">-->
        <!--                                                <i class="ion-eye" style="font-size: 19px;"></i>-->
        <!--                                            </a>-->
        <!--                                        </td>-->
        <!--                                    </tr>-->
                                        </tbody>
                                    </table>
                                    <?php } else{ ?>
                                        <p><?php echo "Không tìm thấy dữ liệu" ; ?></p>
                                    <?php } ?>
                                    <div class="modal fade" id="download" role="dialog">
                                        <div class="modal-dialog modal-lg">
                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Gửi mail</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="row">
                                                                <div class="col-md-4" style="padding: 15px">
                                                                    <label>To: </label>
                                                                </div>
                                                                <div class="col-md-8" style="padding: 15px"><input class="form-control" style="width: 100%" type="text"></div>
                                                                <div class="col-md-4" style="padding: 15px">
                                                                    <label>Subject: </label>
                                                                </div>
                                                                <div class="col-md-8" style="padding: 15px"><input class="form-control" style="width: 100%" type="text"></div>
                                                                <div class="col-md-4" style="padding: 15px">
                                                                    <label>Nội dung email: </label>
                                                                </div>
                                                                <div class="col-md-8" style="padding: 15px">
                                                                    <textarea rows="4" cols="68" class="form-control"></textarea>
                                                                </div>
                                                                <div class="col-md-4" style="padding: 15px">
                                                                    <label>Tài liệu hướng dẫn sử dụng: </label>
                                                                </div>
                                                                <div class="col-md-8" style="padding: 15px">
                                                                    <select style="width: 100%; height: 36px" >
                                                                        <option value="volvo">Tài liệu NV8</option>
                                                                        <option value="saab">Tài liệu VA 9</option>
                                                                        <option value="opel">Tài liệu HO 10</option>
                                                                    </select>
                                                                </div>
                                                                <div class="col-md-4" style="padding: 15px">
                                                                    <label>File: </label>
                                                                </div>
                                                                <div class="col-md-8" style="padding: 15px">
                                                                    <!--                                                                            <i style="font-size: 36px" class="icofont icofont-papers"></i>-->
                                                                    <input type="file" class="form-control">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger waves-effect " data-dismiss="modal">Hủy</button>
                                                    <button type="button" class="btn btn-primary waves-effect " data-dismiss="modal">Gửi mail</button>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: -20px; padding: 0px 25px 25px 25px;">
                                <div class="col-xs-12 col-sm-12 col-md-6">
                                    <div class="dataTables_info" id="footer-search_info" role="status" aria-live="polite">

<!--                                        --><?php //echo $paginator->getTotalItems(); ?><!-- found.-->
<!---->
<!--                                        Showing-->
<!--                                        --><?php //echo $paginator->getCurrentPageFirstItem(); ?>
<!--                                        - entries-->
<!--                                        --><?php //echo $paginator->getCurrentPageLastItem(); ?><!--.-->
                                    </div>
                                </div>
                                <!--                        --><?php //echo 'Bạn đang ở trang ', $page->current, ' / ', $page->total_pages; ?>
                                <div class="col-xs-12 col-sm-12 col-md-6" >
                                    <?php
                                    //                                echo $paginator;
                                    ?>
                                    <ul class="pagination" style="float: right">
                                        <?php if ($paginator->getPrevUrl()): ?>
                                            <li class="paginate_button page-item "><a class="page-link" data-dt-idx="2" tabindex="0" href="<?php echo $paginator->getPrevUrl(); ?>">&laquo; Previous</a></li>
                                        <?php endif; ?>

                                        <?php foreach ($paginator->getPages() as $page): ?>
                                            <?php if ($page['url']): ?>
                                                <li class="paginate_button page-item <?php echo $page['isCurrent'] ? 'active' : ''; ?>" >
                                                    <a href="<?php echo $page['url']; ?>" class="page-link" data-dt-idx="2" tabindex="0"><?php echo $page['num']; ?></a>
                                                </li>
                                            <?php else: ?>
                                                <li class="disabled paginate_button page-item "><span><?php echo $page['num']; ?></span></li>
                                            <?php endif; ?>
                                        <?php endforeach; ?>

                                        <?php if ($paginator->getNextUrl()): ?>
                                            <li class="paginate_button page-item "><a class="page-link" data-dt-idx="2" tabindex="0" href="<?php echo $paginator->getNextUrl(); ?>">Next &raquo;</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--</div>-->
        <!--</div>-->
        <!--</div>-->
        <!--</div>-->
        <!--</div>-->

    </div>
</div>