<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Đơn Hàng</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <div class="row">
                    <div class="col-md-9 text-label-center " style="margin-left: 13%;">
                        <div class="card">
                         <div class="card-header text-createcommand font-faauto font-text">
                          <h4>Chỉnh Sửa Thông Tin Đơn Hàng</h4>
                          <p><?php $this->flashSession->output(); ?></p>
                      </div>
                      <div class="card-block">
                          <?php echo $this->tag->form(["orders/update/" . $orders->id,"autocomplete" => "off",
                           "class" => "form-horizontal",
                           "id"=>"edit_order",
                           "enctype" => "multipart/form-data"]); ?>
                       <div class="form-group row">
                            <div class="col-sm-6">
                                <div class="row">
                                    <label class="col-sm-5 col-form-label text-label-left font-text">Mã đơn hàng:</label>
                                    <div class="col-sm-7">
                                         <input type="text" class="form-control" name="code" readonly=""  value="<?= $orders->order_code?>" >
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="row">
                                    <label class="col-sm-4 col-form-label text-label-left font-text">Phụ trách:</label>
                                    <div class="col-sm-8">
                                        <select name="created_by" class="browser-default custom-select  select2">
                                            <option value="<?= $orders->created_by?>"><?= $orders->created_by?></option>
                                            <?php foreach($teachers as $key=>$val ){
                                               ?>
                                                <option value="<?php echo $val->id ?>"><?php echo $val->fullname?></option>
                                            <?php }?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6">
                                <div class="row">
                                    <label class="col-sm-5 col-form-label text-label-left font-text">Tiêu đề:</label>
                                    <div class="col-sm-7">
                                         <input type="text" class="form-control" name="title"  value="<?= $orders->title?>" >
                                    </div>
                                </div>
                            </div>
                             <div class="col-sm-6">
                                <div class="row">
                                    <label class="col-sm-4 col-form-label text-label-left font-text">Tình trạng đơn hàng:</label>
                                    <div class="col-sm-8">
                                        <select name="status" class="browser-default custom-select  select2">
                                            <option value="<?= $status->id?>"><?= $status->status_name?></option>
                                            <?php foreach($status_name as $key=>$val ) {?>
                                                <option value="<?php echo $val->id ?>"><?php echo $val->status_name?></option>
                                            <?php } ?>
                                        </select>
                                    </div>  

                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label text-label-left font-text pl50"> Ghi chú:</label>
                            <div class="col-sm-10 pl50">
                                <textarea name="contenmail" value="<?= $notes?>"><?= $notes?></textarea>
                                <br/>
                                <p class="erroreditor" style="color: red; font-size: 15px"></p>
                                <p hidden class="results" style="color: green;"></p>
                                <span class="messages"></span>
                            </div>
                        </div>

                <div class="mt40">  
                    <input style="float: left; width: 100px" type="reset" class="btn btn-secondary" value="Reset">
                    <a  style="float: right" href="<?php echo $this->url->get('orders')?>" class ="text-label-right  btn btn-primary m-b-0 ">Đóng</a>
                    <input style="float: right; margin-right: 20px; width: 100px" type="submit" class="btn btn-danger" value="Sửa">
                  
                </div>
            </div>
            </div>
            </form>
<!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>