<div class="page-header">
	<div class="page-block">
		<div class="row align-items-center">
			<div class="col-md-8">
				<div class="page-header-title">
					<h4 class="m-b-10">Thanh toán</h4>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="pcoded-inner-content">
<div class="main-body">
<div class="page-wrapper">
	<div class="page-body">
		<!-- [ page content ] start -->
		<div class="row">
			<div class="col-lg-10" style="padding-left: 220px">
				<div class="card pb10">
					<!-- <div class="card-header -->
					<div class="card-header text-label-center  text-createcommand  font-text font-faauto ">
						<h4>Thêm Thông Tin Nhân Viên</h4>
						<p><?php $this->flashSession->output(); ?></p>
					</div>
						<div class="create-data">
							<div class="card-block">
								<?php echo $this->tag->form(["user/create","autocomplete" => "off",
									"class" => "form-horizontal",
									"id"	=> "create_user",
									"enctype" => "multipart/form-data"]); ?>

									<div class="form-group b-066 row">
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Mã NV:<b style="color: red">(*)</b></label>
												<div class="col-sm-8">
													<input type="text"  placeholder="H29078" id="uservalidate" getdatauser="<?php echo $this->url->get('user/addvalidateuser')?>" maxlength="20" class="form-control" name="username" value="" >
													<span class="messages"></span>
												</div>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Tên NV:<b style="color: red">(*)</b></label>
												<div class="col-sm-8">
													<input type="text"  placeholder="Trịnh Thị Hương"  class="form-control" name="fullname" >
													<span class="messages"></span>
												</div>
											</div>
										</div>
									</div>
									<div class="form-group b-066 row">
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">SĐT:<b style="color: red">(*)</b></label>
												<div class="col-sm-8">
													<input type="text"  placeholder="0968514267" maxlength="10" minlength="10" class="form-control" name="phone">
													<span class="messages"></span>
												</div>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Email: </label>
												<div class="col-sm-8">
													<input type="email"  placeholder="trinhhuong@..." id="emailuser" class="form-control" name="email" >
													<span class="messages"></span>
												</div>
											</div>
										</div>
									</div>
									<div class="form-group b-066 row">
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Địa chỉ: </label>
												<div class="col-sm-8">
													<input type="text"  placeholder="Ha Noi" class="form-control" name="address" value="" >
													<span class="messages"></span>
												</div>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Chức vụ:<b style="color: red">(*)</b></label>
												<div class="col-sm-8">
													<select name="position" class="browser-default custom-select">

														<option value="0"> Nhân viên</option>
														<option value="1"> Cộng tác viên</option>
													</select>
												</div>
											</div>
										</div>
									</div>
									<div class="form-group b-066 row">
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Mật khẩu:<b style="color: red">(*)</b></label>
												<div class="col-sm-8">
													<input  placeholder="Trinhabc2..." type="password" minlength="6" maxlength="15" id="password" class="form-control" name="password">
													<span class="messages"></span>
												</div>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Quyền:<b style="color: red">(*)</b></label>
												<div class="col-sm-8">
													<select name="role" class="browser-default custom-select">

														<option value="1">Nhân Viên</option>
														<option value="0"> Admin</option>
													</select>
												</div>
											</div>
										</div>
									</div>
									<div class="form-group b-066 row">
										<!-- <div class="col-sm-6">
											<div class="row">
												<label class="col-sm-4 col-form-label text-label-right  font-text">Chức vụ (*)</label>
												<div class="col-sm-8">
													<select name="position" class="browser-default custom-select">

														<option value="0"> Nhân viên</option>
														<option value="1"> Cộng tác viên</option>
													</select>
												</div>
											</div>
										</div> -->
									</div>
									<div>
									<a  style="float: right; width: 100px" href="<?php echo $this->url->get('user')?>" class ="btn btn-primary m-b-0 ">Đóng</a>
									<input style="float: right; margin-right: 20px; width: 100px" type="submit" class="btn btn-danger" value="Thêm">

								</div>

								</div>
								
							</form>
						</div>

					</div>

				</div>  

				<!-- site Analytics card end -->
			</div>

			<!-- [ page content ] end -->
		</div>
	</div>
</div>
</div>
</div>	