<div class="page-wrapper">
    <div class="page-body">
        <!-- [ page content ] start -->
        <div class="row">
            <div class="col-lg-10">
                <div class="card ca-details">
                    <div class="card-header font-text text-label-center  font-faauto">
                        <h4>Chi Tiết Thông Tin Nhân Viên <b style="color: chocolate"><i> <?= $users->fullname ?> </i></b> </h4>
                        <p><?php $this->flashSession->output(); ?></p>
                    </div>
                        <div class="create-data">
                            <div class="card-block">
                                <?php echo $this->tag->form(["user/update/". $users->id,"autocomplete" => "off",
                                    "class" => "form-horizontal",
                                    "id"    => "edit_user",
                                    "enctype" => "multipart/form-data"]); ?>

                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Mã NV:</label>
                                                <div class="col-sm-8">
                                                	<label class="col-form-label"><?php echo $users->username?></label>
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Tên NV:</label>
                                                <div class="col-sm-8">
                                                	<label class="col-form-label"><?php echo $users->fullname ?></label>
                                                    
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">SĐT:</label>
                                                <div class="col-sm-8">
                                                	<label class="col-form-label"><?php echo $users->phone ?></label>
                                                  
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Email:</label>
                                                <div class="col-sm-8">
                                                	<label class="col-form-label"><?php echo $users->email?></label>
                                                   
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Địa chỉ:</label>
                                                <div class="col-sm-8">
                                                	<label class="col-form-label"><?php echo $users->address ?></label>
                                                  
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Phòng làm việc :</label>
                                                <div class="col-sm-8">
                                                	<label class="col-form-label"><?php echo $users->department ?></label>
                                                  
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Quyền:</label>
                                                <div class="col-sm-8">
                                                   <label class="col-form-label"><?php echo $users->role  == 0 ? 'Nhân viên' : 'Admin' ?></label>
                                               </div>
                                           </div>
                                       </div>
                                       <div class="col-sm-6">
                                        <div class="row">
                                            <label class="col-sm-4 col-form-label text-label-right  font-text ">Chức vụ:</label>
                                            <div class="col-sm-8">

                                                <label class="col-form-label"><?php echo $users->position == 0 ? "Nhân viên" : "Cộng tác Viên" ?></label>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div>
                                <a  style="float: right; width: 100px" href="<?php echo $this->url->get('user')?>" class ="btn btn-primary m-b-0 ">Đóng</a>
                            </div>
                        </form>
                    </div>

                </div>

            </div>  

            <!-- site Analytics card end -->
        </div>

        <!-- [ page content ] end -->
    </div>
</div>
</div>
</div>