<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Thanh toán</h4>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="pcoded-inner-content">
<div class="main-body">
    <div class="page-wrapper">
    <div class="page-body">
        <!-- [ page content ] start -->
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-header font-text text-label-center  font-faauto">
                        <h4>Chỉnh Sửa Thông Tin Nhân Viên</h4>
                        <p><?php $this->flashSession->output(); ?></p>
                    </div>
                        <div class="create-data">
                            <div class="card-block">
                                <?php echo $this->tag->form(["user/update/". $users->id,"autocomplete" => "off",
                                    "class" => "form-horizontal",
                                    "id"    => "edit_user",
                                    "enctype" => "multipart/form-data"]); ?>

                                    <div class="form-group b-066 row">
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right font-text  ">Mã NV:<b style="color: red">(*)</b></label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" name="username"  readonly=""  value="<?php echo $users->username?>">
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right font-text ">Tên NV:<b style="color: red">(*)</b></label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" name="fullname"  value="<?php echo $users->fullname ?>">
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group b-066 row">
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">SĐT:<b style="color: red">(*)</b></label>
                                                <div class="col-sm-8">
                                                    <input type="text" minlength="10"  maxlength="10" class="form-control" value="<?php echo $users->phone ?>" name="phone" >
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Email:<b style="color: red">(*)</b></label>
                                                <div class="col-sm-8">
                                                    <input type="email" class="form-control" name="email" value="<?php echo $users->email?>" >
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group b-066 row">
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Địa chỉ:<b style="color: red">(*)</b></label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" name="address" value="<?php echo $users->address ?>" >
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div>
                                     <!--    <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right">Phòng làm việc (*)</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" name="department" value="<?php echo $users->department ?>" >
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div> -->
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right font-text ">Chức vụ:</label>
                                                <div class="col-sm-8">
                                                    <select name="position" class="browser-default custom-select">

                                                        <option value="0"<?php echo  $users->position == 0 ?'selected ' : ''?>>Nhân viên
                                                        </option>
                                                        <option value="1"<?php echo $users->position == 1 ?'selected' : ''?> >Cộng tác viên
                                                        </option>
                                                   </select>
                                               </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group b-066 row">
                                       <!--  <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Mật khẩu (*)</label>
                                                <div class="col-sm-8">
                                                    <input type="password" maxlength="25" class="form-control" value="" name="password" >
                                                    <span class="messages"></span>
                                                </div>
                                            </div>
                                        </div> -->
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <label class="col-sm-4 col-form-label text-label-right  font-text ">Quyền:<b style="color: red">(*)</b></label>
                                                <div class="col-sm-8">
                                                    <select name="role" class="browser-default custom-select">

                                                        <option value="0"<?php echo  $users->role == 0 ?'selected ' : ''?>>Nhân viên

                                                    </option>
                                                    <option value="1" <?php echo  $users->role == 1 ?'selected ' : ''?>>Admin

                                                </option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group b-066 row">
                                <!-- <div class="col-sm-6">
                                    <div class="row">
                                        <label class="col-sm-4 col-form-label text-label-right">Chức vụ:</label>
                                        <div class="col-sm-8">
                                            <select name="position" class="browser-default custom-select">

                                                <option value="0"<?php echo  $users->position == 0 ?'selected ' : ''?>>Nhân viên

                                           </option>
                                           <option value="1"<?php echo $users->position == 1 ?'selected' : ''?> >Cộng tác viên

                                       </option>
                                   </select>
                               </div> -->
                           </div>
                       </div>
                   </div>
                    <div>
                <a  style="float: right; width: 100px" href="<?php echo $this->url->get('user')?>" class ="btn btn-primary m-b-0 ">Đóng</a>
                <input style="float: right; margin-right: 20px; width: 100px" type="submit" class="btn btn-danger" value="Sửa">
            </div>
               </div>
        </form>
    </div>

</div>

</div>  

<!-- site Analytics card end -->
</div>

<!-- [ page content ] end -->
</div>
</div>
</div>
</div>
