<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Quản lý giáo viên</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Quản lý giáo viên</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">

        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="row">

                    <!-- site Analytics card start -->
                    
                    <div class="col-lg-12 col-md-12">
                      <div class="card">
                        <div class="card-header font-text font-faauto">
                            <h2>Quản lý tài khoản</h2>
                            <p style="font-size: 20px"><?php $this->flashSession->output(); ?></p>
                        </div>
                        <div class="card-block ">
                            <?php echo $this->tag->form(["user","autocomplete" => "off",
                                "class" => "form-horizontal",
                                "id"=>"create-command",
                                "method" => "get",
                                "enctype" => "multipart/form-data"]); ?>

                                <div class="form-group row">
                                    <div class="col-sm-4">
                                        <div class="row">
                                            <label class="col-sm-5 col-form-label text-label-right font-text">Mã NV:</label>
                                            <div class="col-sm-7">
                                                <input type="text"  placeholder="Nhập mã nhân viên..." class="form-control border-radius" name="username" value="<?php echo $username ? $username :'' ?>" >
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="row">
                                            <label class="col-sm-5 col-form-label text-label-right font-text">Tên NV:</label>
                                            <div class="col-sm-7">
                                                <input type="text"   placeholder="Nhập tên nhân viên..." class="form-control border-radius" name="fullname" value="<?php echo $fullname?>">
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="row">
                                            <label class="col-sm-5 col-form-label text-label-right font-text ">SĐT:</label>
                                            <div class="col-sm-7">
                                                <input type="text"  placeholder="Nhập số điện thoại..." class="form-control border-radius" name="phone" value="<?php echo $phone ? $phone :'' ?>" >
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-4">
                                        <div class="row">
                                            <label class="col-sm-5 col-form-label text-label-right font-text">Từ ngày:</label>
                                            <div class="col-sm-7">
                                                <input name="startDate" value="<?php echo $startDate ? $startDate :'' ?>" class="form-control" type="date"/>
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="row">
                                            <label class="col-sm-5 col-form-label text-label-right">Đến ngày:</label>
                                            <div class="col-sm-7">
                                                <input name="endDate" value="<?php echo $endDate ? $endDate :'' ?>"  class="form-control" type="date"/>
                                                <span class="messages"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                    <!--     <div class="row">
                                            <label class="col-sm-5 col-form-label text-label-right font-text ">Địa chỉ:</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control border-radius "  placeholder="Nhập vào đây để tìm kiếm..." name="address" value="<?php echo $address ? $address :'' ?>" >
                                                <span class="messages"></span>
                                            </div>
                                        </div> -->
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        <div class="pull-right">
                                            <input type="submit" class="btn btn-primary form-control" value="Tìm Kiếm">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        <div> 
                            <a href="<?php echo $this->url->get('user/create')?>" class ="btn btn-warning m-b-0 ">Thêm tài khoản</a>
                            <!-- <div> -->
                                <label class="font-we6 font-da-cursive"  style="float: right; padding-top: 15px;">Tổng số tài khoản: <?= $countuser ?></label>
                                <!-- </div> -->
                            </div>
                        </div>
                        <div class="card-block">
                            <?php if(count($users) <= '0') {?>
                                <label class="col-sm-12" style="text-align: center;" for="">Không có kết quả tìm kiếm</label>
                            <?php } else{?>
                                <div class="table-responsive dt-responsive">
                                    <div id="simpletable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                        <div class="row">
                                            <div class="col-xs-12 col-md-7 col-lg-12">
                                                <table id="dom-table" class="table table-striped table-bordered nowrap dataTable icon-list-demo" role="grid" aria-describedby="simpletable_info">
                                                    <thead>
                                                        <tr role="row">
                                                            <th class="sorting_disabled" rowspan="1" colspan="1"> STT
                                                            </th>
                                                            <th class="sorting_disabled" rowspan="1" colspan="1">Mã NV</th>
                                                            <th class="sorting_disabled" rowspan="1" colspan="1">Tên NV</th>
                                                            <th class="sorting_disabled" rowspan="1" colspan="1">SĐT</th>
                                                            <th class="sorting_disabled" rowspan="1" colspan="1">Email</th>
                                                            <th class="sorting_disabled" rowspan="1" colspan="1">Quyền</th>
                                                            <th class="sorting_disabled" rowspan="1" colspan="1">Ngày Tạo</th>
                                                            <th class="sorting_disabled" rowspan="1" colspan="3">Tùy Chọn</th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>

                                                     <?php foreach($users as $key=>$value) 
                                                     { ?>
                                                        <tr>
                                                            <td><?php echo ($off) + ($key + 1)?></td>
                                                            <td><?php echo $value->username?></td>
                                                            <td><?php echo $value->fullname?></td>
                                                            <td><?php echo $value->phone?></td>
                                                            <td><?php echo $value->email?></td>
                                                            <td><?php echo $value->role == '0' ? 'Nhân viên' : 'Admin'?></td>
                                                            <td><?php echo date("d-m-Y H:m:i", strtotime($value->created_at));?></td>
                                                            <td>
                                                                <a class="btn btn-primary icon-table" href="<?= $this->url->get('user/detail/'.$value->id)?> " title="">
                                                                    <span class='zmdi zmdi-menu'></span>
                                                                </a>
                                                                <a class="btn btn-primary icon-table" href="<?= $this->url->get('user/edit/'.$value->id)?> " title="">
                                                                    <span class='icofont icofont-ui-edit'></span>
                                                                </a>
                                                                <a  href="<?= $this->url->get('user/delete/'.$value->id)?> " class="btn btn-danger icon-table" onclick="return confirm('Xác nhận xóa thành công?');"  title="">
                                                                    <span class='icofont icofont-ui-delete'></span>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    <?php }?>
                                                </tbody>
                                            </table>
                                        <?php } ?>
                                    </div>
                                </div>

                            </div>
                        </div> 
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-5">
                                <div class="dataTables_info" id="footer-search_info" role="status" aria-live="polite">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="footer-search_paginate">
                                    <?php if ($paginator->getNumPages() > 1): ?>
                                        <ul class="pagination">
                                            <?php if ($paginator->getPrevUrl()): ?>
                                                <li class="paginate_button page-item previous" id="footer-search_previous"><a aria-controls="footer-search" data-dt-idx="0" tabindex="0" class="page-link" href="<?php echo $paginator->getPrevUrl(); ?>">&laquo; Previous</a></li>
                                            <?php endif; ?>

                                            <?php foreach ($paginator->getPages() as $page): ?>
                                                <?php if ($page['url']): ?>
                                                    <li class="paginate_button page-item <?php echo $page['isCurrent'] ? 'active' : ''; ?>">
                                                        <a aria-controls="footer-search" data-dt-idx="<?= $key + 1?>" tabindex="0" class="page-link" href="<?php echo $page['url']; ?>"><?php echo $page['num']; ?></a>
                                                    </li>
                                                    <?php else: ?>
                                                        <a aria-controls="footer-search" data-dt-idx="<?= $key +1?>" tabindex="0" class="page-link" href="<?php echo $page['url']; ?>"><?php echo $page['num']; ?></a>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>

                                                <?php if ($paginator->getNextUrl()): ?>
                                                    <li class="paginate_button page-item next" id="footer-search_next"><a aria-controls="footer-search" data-dt-idx="7" tabindex="0" class="page-link" href="<?php echo $paginator->getNextUrl(); ?>">Next &raquo;</a></li>
                                                <?php endif; ?>
                                            </ul>
                                        <?php endif; ?>

                                    </div>
                                </div>
                            </div>
                        </div> 
                    </div>
                    <!-- site Analytics card end -->
                </div>

                <!-- [ page content ] end -->
            </div>
        </div>
        
    </div>
</div>